### ISSUE TITLE
Sort order not respected

### ISSUE THREAD

**Issue by reganp** [patrickkfkan/volumio-youtube2#3]
I love this plugin thank you Patrick!  I noticed a problem after upgrading to latest where the Front Page Section sort order isn't respected i.e. I have to scroll through music channels and playlists before getting to the youtube videos when I'm searching for a particular video.

**Comment by patrickkfkan** [comment]
The Front Page Section settings only apply to the "landing" page of the plugin, which is the page that you see when you first select YouTube2 in Volumio. They do not apply to the search results page, and has been so since day one of this plugin. Search is always performed on channels, playlists and videos and the results are presented in these separate groups.  So what you are seeing now should have been the same as before the update. I have not changed anything concerning this part in the current version.
